---
title: "Untitled"
author: "Kenneth C. Arnold"
date: "6/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readr")
library("tidyverse")
library("ggbeeswarm")
library("afex")
afex::set_sum_contrasts()
```

## Ideas Analysis

```{r read, include=FALSE}
BATCH <- "idea3r5"
DATA_PATH <- paste0("../data/analyzed/idea/", BATCH, "/")
do_read_csv <- function(filename, ...) {
  data <- read_csv(paste0(DATA_PATH, filename), ...);
  stop_for_problems(data);
  data;
}

allData <- do_read_csv("trial.csv",col_types = cols(block = col_factor(c("0", "1", "2"))));
data <- allData %>% subset(should_exclude==FALSE);

expLevel <- do_read_csv("experiment.csv");
ideas <- do_read_csv("ideas.csv");
```

```{r totalTime}
ggplot(expLevel, aes(x=total_time)) + geom_histogram()
```

```{r checkRandomization}
#data %>% group_by(block, condition) %>% summarise(n=n_distinct(participant))
expLevel %>% group_by(condition_order) %>% summarize(n=n())
```

```{r systemFailures}
data %>% group_by(condition, any_requests_returned_empty) %>% summarise(n())
```

```{r numRequests}
data %>% group_by(condition) %>% summarise_at(c("num_inspiration_requests"), mean)
```

```{r requests}
data %>% 
  ggplot(aes(x=condition, y=num_inspiration_requests)) +
    geom_beeswarm() +
    facet_wrap("block")
```

# Manipulation Checks

Indications that the system worked:

- Inspirations got shown, on trials other than norecs.
- Somebody used some word that was a cue word while it was visible.


# Fluency outcome


```{r fluency}
labeledBar <- list(
  stat_summary(geom="bar", fun.y=mean, position="dodge"),
    stat_summary(geom="errorbar", fun.data=mean_se, position=position_dodge(width=.9), width=.4),
    scale_y_continuous(expand=expand_scale(mult=c(0,.05))), # remove the extra spacing at 0
    stat_summary(geom="text", fun.y=mean,
                 aes(label=sprintf("%1.2f", ..y..)),
                 position=position_dodge(width=.9),
                 hjust="middle", vjust="bottom"))

data %>% ggplot(aes(x=condition, y=fluency_5)) + labeledBar# + facet_wrap("block")
```

```{r fluency_analysis}
mixed(fluency_2 ~ condition * block + (1|participant), data = data)
```

```{r}
#ideas %>% group_by(participant, block) %>% mutate(nth=row_number(), frac_less_than=cume_dist(since_start)) #%>% 
ideas %>% groupby(condition) %>% mutate(num_ideas_by_time=)
  #ggplot(aes(x=since_start, y=nth, color=condition))
```

# Subjective Opinions

```{r subjective}
#data %>% ggplot(aes(x=condition, y=brainstorm_sysRelevant)) + labeledBar + facet_wrap("block")
multiBar <- function(measures.to.vis) {
data %>%
    select(participant, condition, block, !!!measures.to.vis) %>%
    gather(measure, value, !!!measures.to.vis) %>%
    mutate(measure=factor(measure, levels=measures.to.vis)) %>%
    ggplot(aes(x=condition, y=value)) +
      labeledBar +
      facet_wrap(vars(measure, block), ncol=3, scales="free", strip.position="top") +
      labs(x="xlabel", y="") +
      theme(
        strip.background = element_blank(),
        panel.spacing.y = unit(2, "lines"),
        axis.line.x = element_blank(),
        legend.position = "bottom")
}

multiBar(c(    "brainstorm_distracting",
    "brainstorm_system_helped"))
```

```{r process}
multiBar(c(
    "brainstorm_fluent",
    "brainstorm_stuck"
));
```

```{r system}
multiBar(c(
    "brainstorm_sysGaveIdeas",
    "brainstorm_sysRelevant",
    "brainstorm_usedInspirations"
  ));
```

```{r}
colnames(data)
```

For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
